curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/1' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":1},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/2' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":2},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/3' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":3},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/4' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":4},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/5' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":5},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/6' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":6},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/7' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":7},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/8' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":8},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/9' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":9},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/10' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":10},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/11' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":11},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/12' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":12},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/13' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":13},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/14' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":14},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/15' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":15},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/16' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":16},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/17' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":17},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> allResults.json
echo "---" >> allResults.json
sleep 1s


