curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/18' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":18},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/19' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":19},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/20' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":20},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/21' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":21},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/22' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":22},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/23' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":23},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/24' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":24},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/25' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":25},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/26' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":26},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/27' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":27},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/28' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":28},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/29' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":29},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/30' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":30},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/31' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":31},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/32' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":32},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/33' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":33},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/34' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":34},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s

curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/35' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":35},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/36' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":36},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/37' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":37},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s


curl 'https://draftfantasyfootball.co.uk/graphql' -H 'Host: draftfantasyfootball.co.uk' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://draftfantasyfootball.co.uk/league/started/k3viHLvuNpaYG6QFJ/team/RiriSDasHQJSKCJii/gameweek/38' -H 'content-type: application/json' -H 'meteor-login-token: gWSTITVwsA3FcO5IlV7It3L3X6T66udMOW_blZGvQHR' -H 'origin: https://draftfantasyfootball.co.uk' -H 'Connection: keep-alive' --data '{"operationName":"getHeadToHeadMatches","variables":{"leagueId":"k3viHLvuNpaYG6QFJ","gameweek":38},"query":"query getHeadToHeadMatches($leagueId: String!, $gameweek: Int!) {\n headToHeadMatches(leagueId: $leagueId, gameweek: $gameweek) {\n _id\n gameweek\n leagueId\n team1 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n team2 {\n _id\n name\n liveGameweekPoints(gameweek: $gameweek)\n user {\n profile {\n firstName\n lastName\n __typename\n }\n __typename\n }\n __typename\n }\n __typename\n }\n}\n"}' >> h2h_data.json
echo "---" >> h2h_data.json
sleep 1s

